version: "3.8"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # Porta para acessar o LocalStack
      - "4510-4559:4510-4559"  # Portas para os serviços individuais
    environment:
      - SERVICES=sqs,dynamodb,redis
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack:/var/lib/localstack"
