server:
  servlet:
    context-path: /orders-management-api
spring:
  threads:
    virtual:
      enabled: true
  main:
    allow-circular-references: true


region: us-east-1

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method: TRACE