server:
  servlet:
    context-path: /orders-management-api
spring:
  threads:
    virtual:
      enabled: true
  main:
    allow-circular-references: true


region: us-east-1
writeRedisUrl: ${{ Redis.REDIS_URL }}
readRedisUrl: ${{ Redis.REDIS_URL }}
dynamoDBUrl: http://dynamodb.railway.internal