server:
  servlet:
    context-path: /orders-management-api
spring:
  threads:
    virtual:
      enabled: true
  main:
    allow-circular-references: true


region: us-east-1
writeRedisUrl: redis://default:nKICaoVYAoZCgjKHvUGRGCLzaqhxuCve@autorack.proxy.rlwy.net:33891
readRedisUrl: redis://default:abc@autorack.proxy.rlwy.net:33891